#!/usr/bin/env zsh

# Check to see if llama-cli is available
if ! command -v llama-cli &>/dev/null; then
	echo "Yo requires llama-cli to be installed. It appears that 'llama-cli' is not installed on your system."
	echo "Would you like to install it now? (y/n): "
	read choice
	if [[ "$choice" =~ ^[yY]$ ]]; then
		echo "Installing llama-cli..."
		pip install llama-cli
		if [ $? -eq 0 ]; then
			echo "llama-cli has been successfully installed."
		else
			echo "There was an error installing llama-cli. Please try installing it manually."
			return 1
		fi
	else
		echo "Installation canceled. Please install llama-cli and try again."
		return 1
	fi
fi

# Check to see if pdftotext is available
if ! command -v pdftotext &>/dev/null; then
  echo "Yo requires pdftotext to be installed. It appears that 'pdftotext' is not installed on your system."
  echo "Would you like to install it now? (y/n): "
  read choice
  if [[ "$choice" =~ ^[yY]$ ]]; then
    echo "Installing pdftotext..."
    pip install pdftotext
    if [ $? -eq 0 ]; then
      echo "pdftotext has been successfully installed."
    else
      echo "There was an error installing pdftotext. Please try installing it manually."
      return 1
    fi
  else
    echo "Installation canceled. Please install pdftotext and try again."
    return 1
  fi
fi

# Yo to the shell
source <(curl -s https://cmccomb.com/yo/src)

# Yo to the ~/.zshrc only if its not already there
sed -i '' '/source <(curl -s https:\/\/cmccomb.com\/yo\/src)/d' ~/.zshrc
echo 'source <(curl -s https://cmccomb.com/yo/src)' >> ~/.zshrc
