#!/usr/bin/env zsh

# Check to see if homebrew is installed and install it if it is not
if ! command -v brew &>/dev/null; then
	echo "Homebrew not found. Installing Homebrew..."
	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo "Homebrew installation complete."
else
	echo "Homebrew is already installed."
fi

# Check to see if llama-cli is installed and install it if it is not
if ! command -v llama-cli &>/dev/null; then
	echo "llama-cli not found. Installing llama.cpp..."
	brew install llama.cpp
	echo "llama.cpp installation complete."
else
	echo "llama-cli is already installed."
fi

# Check to see if pandoc is installed and install it if it is not
if ! command -v pandoc &>/dev/null; then
	echo "Pandoc not found. Installing Pandoc..."
	brew install pandoc
	echo "Pandoc installation complete."
else
	echo "Pandoc is already installed."
fi

# Check to see if pdftotext is installed and install it if it is not
if ! command -v pdftotext &>/dev/null; then
	echo "pdftotext not found. Installing poppler..."
	brew install poppler
	echo "poppler installation complete."
else
	echo "pdftotext is already installed."
fi

# Check to see if gdate is install and install it if it is not
if ! command -v gdate &>/dev/null; then
  echo "gdate not found. Installing coreutils..."
  brew install coreutils
  echo "coreutils installation complete."
else
  echo "gdate is already installed."
fi

# Download the latest version of yo
echo "Downloading the latest version of yo..."
sudo curl --silent https://cmccomb.com/yo/src/main.zsh --output /usr/local/bin/yo
sudo chmod +x /usr/local/bin/yo

# Install the side files
sudo mkdir -p /usr/local/share/yo

# Make an array of files to download
files=(
  "app.zsh"
  "content_extraction.zsh"
  "input_validation.zsh"
  "llms_and_prompts.zsh"
  "logs.zsh"
  "prompt_generators.zsh"
  "repo_and_file_names.zsh"
  "search.zsh"
  "settings.zsh"
  "status_checks.zsh"
  "tokens.zsh"
)

# Download the files
for file in "${files[@]}"; do
  sudo curl --silent "https://cmccomb.com/yo/src/${file}" --output "/usr/local/share/yo/${file}"
done