#!/usr/bin/env zsh
# shellcheck enable=all

# Keep track of paackages to install
brew_packages_to_install=()
dependencies_to_check=(
  "llama-cli:llama.cpp"
  "llama-tokenize:llama.cpp"
  "tesseract:tesseract"
  "pandoc:pandoc"
  "pdftotext:poppler"
)

# Check to see if the command line dependencies are installed and add them to the list if not
for dependency in "${dependencies_to_check[@]}"; do
  # The dependency is in the format of "command:package"
  command="${dependency%%:*}"
  package="${dependency##*:}"
  if ! command -v "${command}" &>/dev/null; then
    brew_packages_to_install+=("${package}")
  fi
done

# Install the command line dependencies
if [[ ${#brew_packages_to_install} -gt 0 ]]; then
  # Check to see if homebrew is installed and install it if it is not
  if ! command -v brew &>/dev/null; then
    echo "Homebrew not found. Installing Homebrew..."
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Homebrew installation complete."
  else
    echo "Homebrew is already installed."
  fi
  echo "Installing command line dependencies..."
  brew install "${brew_packages_to_install[@]}"
  echo "Command line dependencies installed."
else
  echo "Command line dependencies are already installed."
fi


# Download the latest version of yo
echo "Downloading the latest version of yo..."
sudo curl --silent https://cmccomb.com/yo/src/main.zsh --output /usr/local/bin/yo
sudo chmod +x /usr/local/bin/yo

# Install the side files
sudo mkdir -p /usr/local/share/yo

# Make an array of files to download
files=(
	"content_processing.zsh"
	"help_and_version.zsh"
	"input_validation.zsh"
	"installation_management.zsh"
	"llm_session_management.zsh"
	"logging.zsh"
	"prompt_generators.zsh"
	"set_model_names.zsh"
	"settings.zsh"
	"status_checks.zsh"
	"tokens.zsh"
	"web_search.zsh"
)

# Download the files
for file in "${files[@]}"; do
	sudo curl --silent "https://cmccomb.com/yo/src/${file}" --output "/usr/local/share/yo/${file}"
done

# Download the yo models
yo download everything
