# Simple workflow for deploying static content to GitHub Pages
name: Test Install

on:
  # Runs on successful completion of static.yml
  workflow_run:
      workflows: ["Deploy static content to Pages"]
      types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install
        run: zsh <(curl -s https://cmc`comb.com/yo/install)
      - name: Verify
        run: yo say hi