name: Tests
on:
  # Runs on pushes to any branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: sh scripts/install
      - name: Test
        run: sh tests/test_all.sh