name: Tests

on:
  # Runs on successful completion of static.yml
  workflow_run:
      workflows: ["Installation"]
      types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install
        run: zsh <(curl -s https://cmccomb.com/yo/install)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: zsh tests/test_all.zsh